In [2]:
import numpy as np

In [3]:
l=[10,11,12,12]

In [4]:
 arr = np.array(l)

In [5]:
arr

array([10, 11, 12, 12])

In [6]:
arr.size

4

In [7]:
arr.shape

(4,)

In [8]:
arr = np.array([[1,2,3,4],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [9]:
arr.size

8

In [10]:
arr.ndim

2

In [11]:
arr.shape

(2, 4)

In [12]:
arr3 = np.array([[1,2,3,4],[4,5,6,7]])

In [13]:
arr3

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [14]:
arr3.ndim

2

In [15]:
arr3.shape

(2, 4)

In [16]:
arr = np.array([[[1,2,3,4],
       [4,5,6,7]],
               [[1,2,3,4],
        [4,5,6,7]]])

In [17]:
arr

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [18]:
arr.ndim

3

In [19]:
arr2 =np.array ([[1,2,3,4],[4,5,6,7]])

In [20]:
arr2


array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [21]:
arr2.shape 

(2, 4)

In [22]:
arr2.ndim

2

In [23]:
arr3=np.array([[[1,2,3,4,7],[4,5,6,7,7]],
       [[1,2,3,4,7],[4,5,6,7,7]]])

In [24]:
arr3
arr3.ndim

3

In [25]:
arr3.shape

(2, 2, 5)

In [26]:
arr = np.ones(7,dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1])

In [27]:
arr = np.ones((3,5),dtype=int)

In [28]:
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
arr = np.ones(7,dtype=bool)

In [30]:
arr

array([ True,  True,  True,  True,  True,  True,  True])

In [31]:
st1 = [1,2,3,4]
st2 = [2,3,4,5]
st3 = [3,4,5,6]

In [32]:
np.array([st1,st2,st3])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [33]:
arr = np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
arr = np.arange(1,100,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [35]:
arr = np.linspace(1,10,20)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [36]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [38]:
arr = np.arange(1,15).reshape(2,7)
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [39]:
arr = np.arange(1,13).reshape(2,3,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [40]:
arr = np.arange(1,15).reshape(1,2,7)
arr

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]])

In [41]:
arr.ndim

3

In [42]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
arr

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]])

In [45]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [46]:
arr2 = np.array([4,5,6,7])
arr2

array([4, 5, 6, 7])

In [47]:
arr3 = np.add(arr1,arr2)
arr3

array([ 5,  7,  9, 11])

In [48]:
a = np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a1 = np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])

In [51]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr = np.subtract(a,a1)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
arr = np.multiply(a,a1)
arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [54]:
arr = np.divide(a,a1)
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
arr =a.dot(a1)
arr

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [56]:
from sklearn.datasets  import load_digits
digits = load_digits()
digits.images[1]
    

array([[ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.],
       [ 0.,  0.,  0., 11., 16.,  9.,  0.,  0.],
       [ 0.,  0.,  3., 15., 16.,  6.,  0.,  0.],
       [ 0.,  7., 15., 16., 16.,  2.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  3.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  6.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  6.,  0.,  0.],
       [ 0.,  0.,  0., 11., 16., 10.,  0.,  0.]])

In [57]:
a.min()

1

In [58]:
a.max()

9

In [59]:
a.max(axis = 0)

array([7, 8, 9])

In [60]:
a.min(axis = 1)

array([1, 4, 7])

In [63]:
#to check the index of maximum value
np.argmax(a1)
#als can be defined row or columwise
np.argmax(a1,axis = 1)

array([2, 2, 2], dtype=int64)

In [64]:
#to check the index of minimum value
np.argmin(a1)

0

In [66]:
#average value
np.mean(a1)

5.0

In [67]:
#median = center value
np.median(a1)

5.0

In [68]:
#where maximum value is coming
np.std(a1)

2.581988897471611

In [69]:
#variance
#is range which is starting point to end point
np.var(a1)

6.666666666666667

In [70]:
#sqrt
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [71]:
#log
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [76]:
#slicing operation and to cut the image (image crop)
#[row:colimn,row:column]
arr[2:4,2:6]

array([[150]])

In [74]:
arr

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])